language: node_js

node_js:
 - 0.8

notifications:
  email:
    - zcarter@mozilla.com
    - rkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#picl"
    use_notice: false
    skip_join: false

before_install:
  - if [[ "$SUT" == "couchbase" ]]; then ./scripts/setup_couchbase.sh; fi

env:
  - KVSTORE_BACKEND=couchbase SUT=couchbase CB_URL="http://packages.couchbase.com/releases/2.0.1/couchbase-server-enterprise_x86_64_2.0.1.deb" CB_DEB="couchbase-server-enterprise_x86_64_2.0.1.deb" CB_VER="2.0.1" CB_CONFIG_CMD="/opt/couchbase/bin/cbepctl localhost:11210 set flush_param flushall_enabled true"
  - KVSTORE_BACKEND=memory
