language: node_js

node_js:
 - 0.8

notifications:
  email:
    - zcarter@mozilla.com
    - rkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#picl"
    use_notice: false
    skip_join: false

before_install:
  - wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - echo deb http://packages.couchbase.com/snapshot/ubuntu oneiric oneiric/main | sudo tee /etc/apt/sources.list.d/couchbase.list
  - sudo apt-get update
  - sudo apt-get -y install libcouchbase2-dev

env:
  - KVSTORE_BACKEND=memory
  - KVSTORE_BACKEND=couchbase
